name: Deploy Vanilla JS App
on: push
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    name: checkout code 
    uses: actions/checkout@v3
    name: Deploy to GitHub Pages
    uses: JamesIves/github-pages-deploy-action@4.1.0
    with: 
     branch: ra-pages
     folder: src